name: Approval workflow
on: pull_request_review
job:
  labelWhenApproved:
    runs-on: ubuntu-latest
  step:
  - name: reminder
    use: pullreminders/label-when-approved-action@master
    env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
    
    
